### ISSUE TITLE
States Parties Map

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#100]
@budparr 

So as discussed, we will put territories into draft mode, thus taking them out of the list of countries. However, these territories should correspond in color on the map with the sovereign states that control them (i.e. Greenland is controlled by Denmark, so should stay States Parties blue).

**Comment by budparr** [comment]
Don't put them in draft mode just yet until I look at how it will effect the map

**Comment by budparr** [comment]
So there's two things. 

One, Greenland should have the "State Party" switch turned on, and then a note (I think in the "note" field toward the bottom) stating that it's controlled by Denmark. 

That rule should hold for all of them, instead of making them a draft.

Then, I need to come up with some rule that makes them show up on the map, but not on the list. (because changing them to draft will take them off both).

**Comment by budparr** [comment]
I think I'm going to have to give you a switch saying "Territory?" to not show on the list. That's a good way from a structured content perspective, but if there are cases where there is a territory that you want to show, we'd end up breaking the rule (the rule being that "territories do not show on the States Parties table."

Or perhaps it should be more straightforward and say "Show on States Parties Table?"

To be clear, I don't like the latter solution because it doesn't separate content from presentation, but if you think option one above won't work, we can do the second.

Hate to add yet another field, but I don't think there's anything in the existing data to make this distinction.

**Comment by kiphale** [comment]
Well I think she was putting them in draft mode. I will have her revert

**Comment by budparr** [comment]
Sorry, but I didn't originally understand that they had to show in one place, but not the other.

**Comment by kiphale** [comment]
Don't be sorry! Like I knew either. 

I defer to you as to what is the best tech solution to the problem.

**Comment by budparr** [comment]
But you have to answer my question. 

I'd prefer to include a switch that says if it is a territory. So, if it's a territory, I will leave it off the table view.

However, if there are instances where you want a territory to show on the table view, then I want to use the second rule (because I don't want us to break data for presentation).
