### ISSUE TITLE
Burundi

### ISSUE THREAD

**Issue by kiphale** [ABA-Center-for-Human-Rights/aba-icc#114]
Why is Burundi's information doubling up?

![image](https://cloud.githubusercontent.com/assets/8195536/14928098/dca2439c-0e23-11e6-9176-8c7e520dfdef.png)

**Comment by budparr** [comment]
Because it was entered in two places. 

The country page (where it doesn't belong):
https://app.cloudcannon.com/client_editor/19590/site#/site/19590/collections/_countries/burundi.md

The Situations page:
https://app.cloudcannon.com/client_editor/19590/site#/site/19590/collections/_situations/burundi.md

I removed it for you, and I'll make an issue to create some documentation. It's a complex site, so I don't blame anyone for not getting where everything goes.
